- .github/workflows/pylint.yml
- .github/workflows/test.yml
- .gitignore
- .idea/.gitignore
- .idea/algorithmic-trading.iml
- .idea/encodings.xml
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- main.py
- requirements.txt
- setup.sh
- tests/sample_test.py
#3
- setup for pycharm
- setup github workflows to run on PR
- setup a setup.sh file for onboarding
- make a requirement.txt file
> Setting up algorithmic trading

- .gitignore
- Makefile
> Run unit tests locally

- bin/commit-msg.sh
- setup.sh
topic/#8
- We should always be mentioning the issue number in the commit message
> add git commit labeler check

- Makefile
- README.md
- tests/sample_test.py
> Write onboarding information on the readme

- member_list.txt
topic/#13
- Added the member list for people to work on.
- Added my name in the member list text file.
> Added member list

- member_list.txt
> added Niranjan Hablani

- member_list.txt
> Added Param Sha to member_list

- .github/workflows/notify_ready_for_merge.yml
> Adding notify for ready for merge

- .github/PULL_REQUEST_TEMPLATE.md
topic/#40
- Added PR description checklist
> Adding a PR description mentioning these steps

- member_list.txt
> Added Param Patel member_list.txt

- member_list.txt
> added Harsimar Kaur to member_list.

- member_list.txt
Topic/#13
Added Sandeep Kumar to the Member List
> On boarding - Sandeep Kumar

- .github/workflows/test.yml
- Makefile
- interfaces/sample_interface.py
- src/sample_impl.py
- tests/sample_test.py
> Added sample interface and implementation

- member_list.txt
> Added "Kamal Kandpal" to member_list.txt

- member_list.txt
- Added Manan Jain to members list
> [topic/#20] - Added Manan Jain to the member list

- member_list.txt
> Added Aryan Patel to member list

- member_list.txt
topic/#19
Hi, I'm not sure if this is what I'm supposed to do but I added my name to member_list.txt and committed the changes to my branch. Was I supposed to write Ready for Review as the title?
Thanks! 
> Github Member Onboarding [Lena Ye]

- data/data.sample
- src/common/config.py
- src/common/data_collection.py
- tests/common/data_collection_test.py
topic/#57
- Added global constants.
- added setup data function.
- updated unit tests.
> make a folder for data collection

- member_list.txt
> Added Tra Luu to member list

- interfaces/preprocessor_interface.py
topic/#56
This PR introduces an abstract base class, `IPreProcessData`, which serves as a standardized interface for data preprocessing. The interface enforces a structured and consistent approach to handling preprocessing across different datasets and use cases.
Changes Introduced:
- Created an abstract base class IPreProcessData using Python's ABC module.
- Defined essential preprocessing methods as abstract methods:
- load_data(file_path): Loads data and stores it in Parquet format.
- missing_values(dataframe, strategy): Handles missing values using different strategies.
- remove_duplicate_timestamps(dataframe, column): Removes duplicate timestamp values when necessary.
- remove_outliers(dataframe, column, method): Identifies and removes outliers using methods like Z-score.
NOTE: **DO …
> Added a Preprocessor Interface python file to interfaces.

- src/algorithms/hidden_markov_model_impl.py
- src/preprocessing/hma_preprocessor_impl.py
- tests/algorithms/hidden_markov_model_impl_test.py
- tests/preprocessing/hmm_preprocessor_impl_test.py
- tests/preprocessing/sma_preprocessor_impl_test.py
topic/#71
- Create HiddenMarkovModelAlgorithmImpl
- Create HMMPreProcessorImpl
- Create HiddenMarkovModelAlgorithmImplTest
- Create HMMPreProcessorImplTest
> Setup the files for HMM tasks

- src/preprocessing/hma_preprocessor_impl.py
- src/preprocessing/sma_preprocessor_impl.py
> Copy paste errors

- member_list.txt
> topic/#27 - added Sumaiya Mayisha Shahadot to member list
